### ISSUE TITLE
EmptyStaticCreds: static credentials are empty

### ISSUE THREAD

**Issue by ryjogo** [glnds/dyndns_route53#1]
Cool project, but i'm getting EmptyStaticCreds on a new build from src. Any idea?

panic: EmptyStaticCreds: static credentials are empty

goroutine 1 [running]:
panic(0x705b40, 0xc420018400)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.perror(0x7f27da9489d0, 0xc420018400, 0xc420113980)
	/root/updateIP/dyndns_route53/dyndns_route53.go:37 +0x10a
main.main()
	/root/updateIP/dyndns_route53/dyndns_route53.go:118 +0x1119

**Comment by ryjogo** [comment]
fixed.. updated config.json values to values in code.. also removed static hostname in code..

**Comment by glnds** [comment]
@rjgough did you had to adjust any code? If so, please make a pull request. About config.json, maybe the readme is not clear enough? Any feedback is more then welcome!

**Comment by ryjogo** [comment]
Sure will sent a pull request later on today
